
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorjava;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 10;
  public static final int DISTINTO = 52;
  public static final int ABRIR_LLAVE = 37;
  public static final int CASO = 31;
  public static final int PUBLICO = 18;
  public static final int PUNTOYCOMA = 9;
  public static final int INTERRUMPUTOR = 28;
  public static final int ARGUMENTO = 58;
  public static final int ENTERO = 2;
  public static final int SI = 27;
  public static final int RESTA = 42;
  public static final int PRINCIPAL = 56;
  public static final int MENORIGUAL = 49;
  public static final int NOT = 47;
  public static final int AND = 45;
  public static final int PRIVADO = 17;
  public static final int MAYORQUE = 54;
  public static final int IGUAL = 34;
  public static final int PAQUETE = 24;
  public static final int SINO = 32;
  public static final int OR = 46;
  public static final int VALORINT = 12;
  public static final int CORCHETE_CIERRA = 40;
  public static final int MIENTRAS = 29;
  public static final int SUMA = 41;
  public static final int IMPORTAR = 23;
  public static final int MAYORIGUAL = 48;
  public static final int CERRAR_PARENTESIS = 36;
  public static final int EOF = 0;
  public static final int HUECO = 55;
  public static final int ESTATICO = 20;
  public static final int CLASE = 22;
  public static final int error = 1;
  public static final int CADENA = 16;
  public static final int COMENTARIO = 25;
  public static final int CERRAR_LLAVE = 38;
  public static final int RESIDUO = 50;
  public static final int VALORDOBLE = 14;
  public static final int DOBLE = 4;
  public static final int MENORQUE = 53;
  public static final int ABRIR_PARENTESIS = 35;
  public static final int VALORBOOLEANO = 15;
  public static final int ROMPER = 33;
  public static final int CORCHETE_ABRE = 39;
  public static final int PUNTO = 11;
  public static final int VARIABLE = 57;
  public static final int IGUALIGUAL = 51;
  public static final int VALORFLOAT = 13;
  public static final int FALSO = 8;
  public static final int HACER = 30;
  public static final int PROTEGIDO = 19;
  public static final int BOOLEANO = 5;
  public static final int STRING = 6;
  public static final int PARA = 26;
  public static final int VERDADERO = 7;
  public static final int DIVISION = 43;
  public static final int DEFECTO = 21;
  public static final int FLOTANTE = 3;
  public static final int MULTIPLICACION = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "FLOTANTE",
  "DOBLE",
  "BOOLEANO",
  "STRING",
  "VERDADERO",
  "FALSO",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "PUNTO",
  "VALORINT",
  "VALORFLOAT",
  "VALORDOBLE",
  "VALORBOOLEANO",
  "CADENA",
  "PRIVADO",
  "PUBLICO",
  "PROTEGIDO",
  "ESTATICO",
  "DEFECTO",
  "CLASE",
  "IMPORTAR",
  "PAQUETE",
  "COMENTARIO",
  "PARA",
  "SI",
  "INTERRUMPUTOR",
  "MIENTRAS",
  "HACER",
  "CASO",
  "SINO",
  "ROMPER",
  "IGUAL",
  "ABRIR_PARENTESIS",
  "CERRAR_PARENTESIS",
  "ABRIR_LLAVE",
  "CERRAR_LLAVE",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "AND",
  "OR",
  "NOT",
  "MAYORIGUAL",
  "MENORIGUAL",
  "RESIDUO",
  "IGUALIGUAL",
  "DISTINTO",
  "MENORQUE",
  "MAYORQUE",
  "HUECO",
  "PRINCIPAL",
  "VARIABLE",
  "ARGUMENTO"
  };
}

